version: "3"
services:
  api:
    restart: always
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/app/
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.dbservice
    environment:
      - POSTGRES_USER=tom
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=calc_db
    ports:
      - "5432:5432"
